
<div>
    <form action="/user/register" method="POST">
        <div>
            Username: <input type="text" name="username" />
        </div>
        <div>
            Password: <input type="password" name="password" />
        </div>
        <div>
            Email: <input type="email" name="email" />
        </div>
        <div>
            Name: <input type="text" name="name" />
        </div>
        <div>
            <button id="submit">Submit</button>
        </div>
    </form>
</div>
<div id="results">

</div>